//C Include to make network work
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <arpa/inet.h>
#include <string.h>
#include <sys/socket.h>
#include <unistd.h>
// Include custom libraries
#include "../protocol_lib/protocol_lib.h"


#define SERVER_IP "127.0.0.1"
#define SERVER_PORT 8080
#define SQLITE_MAX_SIZE 99

int CreateSocket();
void handle_get_movie_list(int socket);
void handle_get_shows(int socket);
void handle_reserve_seats(int socket);
void handle_add_movie(int socket);
void handle_add_show(int socket);
u_int8_t handle_login(int socket);
u_int8_t handle_logout(int socket);
u_int8_t Connect(int socket);
u_int8_t Disconnect(int client_fd);

///Code generated by github copilot need to be modified
int main(int argc,char* argv[]) {
    int client_fd;
    int sock;
    if ((sock = socket(AF_INET, SOCK_STREAM, 0)) < 0)  {
            perror("Socket failed");
            exit(EXIT_FAILURE);
        }
    int choix;
    u_int8_t fini = 0,connected = 0,logged = 0;
    while(!fini)
    {
        if (argc == 2) { choix = atoi(argv[1]); fini = 1; }
        else choix;
        {
            printf("\n");
            printf("---------------------------------------------------------------------------\n");
            printf("--- Gestionnaire de Cinéma -----------------------------------connected :%d\n", connected);
            printf("----Please be connected before using features--------------------logged: %d\n", logged);
            printf(" 1. Get movie list\n");
            printf(" 2. Get available show for a Movies\n");
            printf("Admin features\n");
            printf(" 3. Reserve x seats for a show\n");
            printf(" 4. Add a movie\n");
            printf(" 5. Add a show\n");
            printf("Authentication features\n");
            printf(" 6. Login\n");
            printf(" 7. Logout\n");
            printf("Network features\n");
            printf(" 8. Connect\n");
            printf(" 9. Disconnect\n");
            printf(" 0. Exit\n");
            printf("  Choix : ");
            scanf("%d", &choix);fflush(stdin);
            getchar(); // to consume the newline character left by scanf
        }
        switch(choix)
        {
            case 1 : if(connected)handle_get_movie_list(sock);else printf("Please connect"); break;
            case 2 : if(connected)handle_get_shows(sock);else printf("Please connect"); break;
            case 3 : if(connected&&logged)handle_reserve_seats(sock);else printf("Please connect"); break;
            case 4 : if(connected&&logged)handle_add_movie(sock);else printf("Please connect"); break;
            case 5 : if(connected&&logged)handle_add_show(sock);else printf("Please connect"); break;
            case 6 : if(connected)logged = handle_login(sock);else printf("Please connect"); break;
            case 7 : if(connected)logged = handle_logout(sock);else printf("Please connect"); break;
            case 8 : if(client_fd = Connect(sock)) connected = 1; else connected = 0; break;
            case 9 : if(Disconnect(client_fd)) connected = 0; else connected = 1; break;
            default : fini = 1 ; break;
        }
    }
    return 0;
}
void handle_get_movie_list(int socket){
    struct packet * packet = malloc(sizeof(struct packet));
    packet->type = 0x01;
    packet->Status = 0x01;
    packet->payload = NULL;
    send_packet(socket,packet);
    deletePayload(&packet->payload);
    //Wait to recv the packet
    packet =  recv_packet(socket);
    struct Parameter * current = packet->payload;
    int count = 0;uint8_t last = 0;
    if(current == NULL)
    {
        printf("No movie available\n");
        return;
    }else{
        while (current->next != NULL || last == 1)
        {
            printf("%s",current->data);
            if(count%2 == 0)
                printf(",");
            else
                printf("\n");
            current = current->next;
            count++;
            if(last == 1)
                break;
            if(current->next == NULL)
                last = 1;
        }
    }
    deletePayload(&packet->payload);
    free(packet);
}
void handle_get_shows(int socket) {
    printf("Please enter the movie id :");
    char * movie_id = malloc(5*sizeof(char));
    scanf("%4s", movie_id);fflush(stdin);
    struct packet * packet = malloc(sizeof(struct packet));
    packet->type = 0x02;
    packet->Status = 0x01;
    packet->payload = createParameter(movie_id);
    send_packet(socket,packet);
    deletePayload(&packet->payload);
    //Wait to recv the packet
    packet =  recv_packet(socket);
    struct Parameter * current = packet->payload;
    if(current != NULL)
    {
        int count = 0;uint8_t last = 0;
        while (current->next != NULL || last == 1)
        {
            printf("%s",current->data);
            if(count%5 == 0 && count != 0)
                printf("\n");
            else
                printf(",");
            current = current->next;
            count++;
            if(last == 1)
                break;
            if(current->next == NULL)
                last = 1;
        }
        deletePayload(&packet->payload);
    }else
    {
        printf("No show available for this movie\n");
    }
    free(packet);
}
void handle_add_movie(int socket) {
    char title[SQLITE_MAX_SIZE];
    char genre[SQLITE_MAX_SIZE];
    char director[SQLITE_MAX_SIZE];
    char release_date[SQLITE_MAX_SIZE];
    char entry_ok = 0;
    while(entry_ok == 0)
    {
        printf("Enter movie title: ");
        fgets(title, SQLITE_MAX_SIZE, stdin);fflush(stdin);

        printf("\nEnter movie genre: ");
        fgets(genre, SQLITE_MAX_SIZE, stdin);fflush(stdin);

        printf("\nEnter movie director: ");
        fgets(director, SQLITE_MAX_SIZE, stdin);fflush(stdin);

        printf("\nEnter movie release date (YYYY-MM-DD): ");
        fgets(release_date, SQLITE_MAX_SIZE, stdin);fflush(stdin);

        printf("\n\n=== Entered Information ===\n");
        printf("Title: %s\n", title);
        printf("Genre: %s\n", genre);
        printf("Director: %s\n", director);
        printf("Release Date: %s\n", release_date);

        int confirm_ok = 0;
        int entry_ok;

        while (confirm_ok == 0) {
            printf("Is this information correct? (y/n): ");
            entry_ok = getchar();
            // Consume extra characters in input buffer until newline
            int c;
            while ((c = getchar()) != '\n' && c != EOF);
            if (entry_ok == 'y' || entry_ok == 'Y') {
                confirm_ok = 1;
                entry_ok = 1;
            } else if (entry_ok == 'n' || entry_ok == 'N') {
                confirm_ok = 1;
                entry_ok = 0;
            } else {
                printf("Invalid input. Please try again.\n");
                confirm_ok = 0;
            }
        }
    }
    struct packet * packet = malloc(sizeof(struct packet));
    packet->type = 0x04;
    packet->Status = 0x01;
    packet->payload = createParameter(title);
    appendParameter(packet->payload,genre);
    appendParameter(packet->payload,director);
    appendParameter(packet->payload,release_date);
    send_packet(socket,packet);
    deletePayload(&packet->payload);
    free(packet);
    packet = recv_packet(socket);
    if(packet->Status == 0x01)
    {
        printf("Show added successfully\n");
    }
    else
    {
        printf("Error adding show\n");
    }
    deletePayload(&packet->payload);
    free(packet);

}

void handle_add_show(int socket) {
    char movie_id[SQLITE_MAX_SIZE];
    char nbr_seats[SQLITE_MAX_SIZE];
    char start_time[SQLITE_MAX_SIZE];
    char end_time[SQLITE_MAX_SIZE];
    char show_date[SQLITE_MAX_SIZE];
    uint8_t entry_ok = 0;
    while(entry_ok == 0)
    {
        printf("\nEnter movie ID: ");
        fgets(movie_id, SQLITE_MAX_SIZE, stdin);
        fflush(stdin);
        printf("\nEnter number of seats: ");
        fgets(nbr_seats, SQLITE_MAX_SIZE, stdin);
        fflush(stdin);
        printf("\nEnter start time (HH:MM): ");
        fgets(start_time, SQLITE_MAX_SIZE, stdin);
        fflush(stdin);
        printf("\nEnter end time (HH:MM): ");
        fgets(end_time, SQLITE_MAX_SIZE, stdin);
        fflush(stdin);
        printf("\nEnter show date (YYYY-MM-DD): ");
        fgets(show_date, SQLITE_MAX_SIZE, stdin);
        fflush(stdin);
        // Displaying entered show information
        printf("\n\n=== Entered Show Information ===\n");
        printf("Movie ID: %s\n", movie_id);
        printf("Number of Seats: %s\n", nbr_seats);
        printf("Start Time: %s\n", start_time);
        printf("End Time: %s\n", end_time);
        printf("Show Date: %s\n", show_date);
        uint8_t confirm_ok = 0;
        while (confirm_ok == 0) {
            printf("Is this information correct? (y/n): ");
            entry_ok = getchar();
            // Consume extra characters in input buffer until newline
            int c;
            while ((c = getchar()) != '\n' && c != EOF);
            if (entry_ok == 'y' || entry_ok == 'Y') {
                confirm_ok = 1;
                entry_ok = 1;
            } else if (entry_ok == 'n' || entry_ok == 'N') {
                confirm_ok = 1;
                entry_ok = 0;
            } else {
                printf("Invalid input. Please try again.\n");
                confirm_ok = 0;
            }
        }
    }
    struct packet * packet = malloc(sizeof(struct packet));
    packet->type = 0x05;
    packet->Status = 0x01;
    packet->payload = createParameter(movie_id);
    appendParameter(packet->payload,nbr_seats);
    appendParameter(packet->payload,start_time);
    appendParameter(packet->payload,end_time);
    appendParameter(packet->payload,show_date);
    send_packet(socket,packet);
    deletePayload(&packet->payload);
    free(packet);
    packet = recv_packet(socket);
    if(packet->Status == 0x01)
    {
        printf("Show added successfully\n");
    }
    else
    {
        printf("Error adding show\n");
    }
    deletePayload(&packet->payload);
    free(packet);
}

void handle_reserve_seats(int socket) {
    // TODO: Implement the logic for reserving seats
    char show_id[SQLITE_MAX_SIZE];
    char nbr_seats[SQLITE_MAX_SIZE];
    uint8_t entry_ok = 0;
    while(entry_ok == 0)
    {
        printf("\nEnter show ID: ");
        scanf("%6s", show_id);
        fflush(stdin);

        printf("\nEnter number of seats: ");
        scanf("%6s", nbr_seats);
        fflush(stdin);

        // Displaying entered show information
        printf("\n\n=== Entered Reservation Information ===\n");
        printf("Show ID: %s\n", show_id);
        printf("Number of Seats: %s\n", nbr_seats);

        uint8_t confirm_ok = 0;
        while (confirm_ok == 0) {
            printf("Is this information correct? (y/n): ");
            entry_ok = getchar();

            // Consume extra characters in input buffer until newline
            int c;
            while ((c = getchar()) != '\n' && c != EOF);

            if (entry_ok == 'y' || entry_ok == 'Y') {
                confirm_ok = 1;
                entry_ok = 1;
            } else if (entry_ok == 'n' || entry_ok == 'N') {
                confirm_ok = 1;
                entry_ok = 0;
            } else {
                printf("Invalid input. Please try again.\n");
                confirm_ok = 0;
            }
        }
    }
    struct packet * packet = malloc(sizeof(struct packet));
    packet->type = 0x03;
    packet->Status = 0x01;
    packet->payload = createParameter(show_id);
    appendParameter(packet->payload,nbr_seats);
    send_packet(socket,packet);
    deletePayload(&packet->payload);
    free(packet);
}

u_int8_t handle_login(int socket) {
    char username[26];
    char password[26];
    printf("---------------------------------------------------------------------------\n");
    printf("-------Login Wizard--------------------------------------------------------\n");
    printf("---------------------------------------------------------------------------\n\n");
    printf("Please Enter your username (max 25 char): ");
    scanf("%25s", username);fflush(stdin); //fix overflow
    printf("\nPlease Enter your password (max 25 char): ");
    scanf("%25s", password);fflush(stdin); //fix overflow
    struct packet * packet = malloc(sizeof(struct packet)); //Not using malloc because we don't need to keep it
    packet->type = 0x06;
    packet->Status = 0x01;
    packet->payload = createParameter(username);
    appendParameter(packet->payload,password);
    send_packet(socket,packet);
    deletePayload(&packet->payload);
    //Wait to recv the packet
    packet =  recv_packet(socket);
    if(packet->Status == 0x01)
    {
        printf("Login successful\n");
        return 1;
    }
    else
    {
        printf("Login failed\n");
        return 0;
    }
    free(packet);
}
u_int8_t handle_logout(int socket) {
    struct packet * packet = malloc(sizeof(struct packet)); //Not using malloc because we don't need to keep it
    packet->type = 0x07;
    packet->Status = 0x01;
    packet->payload = NULL;
    send_packet(socket,packet);
    deletePayload(&packet->payload);
    //Wait to recv the packet
    packet =  recv_packet(socket);
    if(packet->Status == 0x01)
    {
        printf("Logout successful\n");
        return 1;
    }
    else
    {
        printf("Logout failed\n");
        return 0;
    }
    return 0;
}
u_int8_t Connect(int socket) {
    struct sockaddr_in sockaddr;
    char * ip;
    char * port;
    port = malloc(5*sizeof(char)); //Warning overflow if too long port
    ip = malloc(15*sizeof(char)); //Warning overflow if too long ip
    int port_int;
    int client_fd;
    printf("---------------------------------------------------------------------------\n");
    printf("-------Connection Wizard---------------------------------------------------\n");
    printf("---------------------------------------------------------------------------\n\n");
    printf("Please Enter the targetted IP Address (expample 127.0.0.1 ): ");
    scanf("%14s", ip);fflush(stdin); //fix overflow
    printf("\n");
    //Convert IP address to right format
    if (inet_pton(AF_INET, ip, &sockaddr.sin_addr)<= 0)
    {
        perror("\nInvalid sin_addr/ sin_addr not supported \n");
        exit(EXIT_FAILURE);
    }
    printf("Please Enter the port (example 5050): ");
    scanf("%4s", port);fflush(stdin);
    sockaddr.sin_family=AF_INET; //IPV4
    port_int = atoi(port);
    sockaddr.sin_port = htons(port_int);
    if ((  client_fd = connect(socket, (struct sockaddr*)&sockaddr,sizeof(sockaddr))) < 0)
    {
        perror("Connection failed");
        exit(EXIT_FAILURE);
    }
    return 1;
}

u_int8_t Disconnect(int client_fd) {
    close(client_fd);
    printf("-----------------You're disconnected---------------------------------------\n");
    return 1;
}