//C Include to make network work
#include <stdlib.h>
#include <stdio.h>
#include <string.h> 
#include <arpa/inet.h>
#include <string.h>
#include <sys/socket.h>
#include <unistd.h>
// Include custom libraries
#include "../protocol_lib/protocol_lib.h"


#define SERVER_IP "127.0.0.1"
#define SERVER_PORT 8080

int CreateSocket();
int Menu(u_int8_t connected);
void handle_get_movie_list(int socket);
void handle_add_movie(int socket);
void handle_add_show(int socket);
void handle_reserve_seats(int socket);
int Connect(int socket);
int Disconnect(int client_fd);

///Code generated by github copilot need to be modified
int main(int argc,char* argv[]) {
    int client_fd;
    int sock;
    if ((sock = socket(AF_INET, SOCK_STREAM, 0)) < 0)  {
            perror("Socket failed");
            exit(EXIT_FAILURE);
        }
    int choix;
    u_int8_t fini = 0,connected = 0;
    while(!fini)
    {
        if (argc == 2) { choix = atoi(argv[1]); fini = 1; }
        else choix = Menu(connected);
        switch(choix)
        {
            case 1 : if(connected)handle_get_movie_list(sock);else printf("Please connect"); break;
            case 2 : if(connected)handle_add_movie(sock);else printf("Please connect"); break;
            case 3 : if(connected)handle_add_show(sock);else printf("Please connect"); break;
            case 4 : if(connected)handle_reserve_seats(sock);else printf("Please connect"); break;
            case 5 : if(client_fd = Connect(sock)) connected = 1; else connected = 0; break;
            case 6 : if(client_fd = Connect(sock)) connected = 1; else connected = 0; break;
            case 7 : if(Disconnect(client_fd)) connected = 0; else connected = 1; break;
            default : fini = 1 ; break;
        }
    }
    return 0;
}
int Menu(u_int8_t connected)
{
    int ch;
    printf("\n");
    printf("---------------------------------------------------------------------------\n");
    printf("--- Gestionnaire de Cinéma ------------------------------------------------\n");
    printf("----Please be connected before using features-------------    connected :%d\n", connected);
    printf(" 1. Get movie list\n");
    printf(" 2. Get available seats for a show\n");
    printf(" 3. Reserve x seats for a movie\n");
    printf(" 4. Add a movie\n");
    printf(" 5. Connect\n");
    printf(" 6. Connect\n");
    printf(" 7. Disconnect\n");
    printf(" 8. Exit\n");
    printf("  Choix : ");
    scanf("%d", &ch);fflush(stdin);
    getchar(); // to consume the newline character left by scanf
    return ch;
}

void handle_get_movie_list(socket){
    struct packet * packet = malloc(sizeof(struct packet));
    packet->type = 0x01;
    packet->Status = 0x01;
    packet->payload_size = 0;
    packet->payload = NULL;
    send_packet(socket,packet);
    //Wait to recv the packet
    packet =  recv_packet(socket);
    struct Parameter * current = packet->payload;
    while (current->next != NULL)
    {
        printf("%s\n",current->data);
        current = current->next;
    }
    destroy_packet(packet);
}

void handle_add_movie(int socket) {
    // TODO: Implement the logic for adding a movie
}

void handle_add_show(int socket) {
    // TODO: Implement the logic for adding a show
}

void handle_reserve_seats(int socket) {
    // TODO: Implement the logic for reserving seats
}

int Connect(int socket) {
    struct sockaddr_in sockaddr;
    char * ip;
    char * port;
    port = malloc(5*sizeof(char)); //Warning overflow if too long port
    ip = malloc(15*sizeof(char)); //Warning overflow if too long ip
    int port_int;
    int client_fd;
    printf("---------------------------------------------------------------------------\n");
    printf("-------Connection Wizard---------------------------------------------------\n");
    printf("---------------------------------------------------------------------------\n\n");
    printf("Please Enter the targetted IP Address (expample 127.0.0.1 ): ");
    scanf("%14s", ip);fflush(stdin); //fix overflow
    printf("\n");
    //Convert IP address to right format
    if (inet_pton(AF_INET, ip, &sockaddr.sin_addr)<= 0) 
    {
        perror("\nInvalid sin_addr/ sin_addr not supported \n");
        exit(EXIT_FAILURE);
    }
    printf("Please Enter the port (example 5050): ");
    scanf("%4s", port);fflush(stdin);
    sockaddr.sin_family=AF_INET; //IPV4
    port_int = atoi(port);
    sockaddr.sin_port = htons(port_int);
    if ((  client_fd = connect(socket, (struct sockaddr*)&sockaddr,sizeof(sockaddr))) < 0) 
    {
        perror("Connection failed");
        exit(EXIT_FAILURE);
    }
    return 1;
}

int Disconnect(int client_fd) {
    close(client_fd);
    printf("-----------------You're disconnected---------------------------------------\n");
    return 1;
}